# fly.toml app configuration file generated for apis-0113 on 2023-05-17T21:47:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apis-0113"
primary_region = "qro"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
